### ISSUE TITLE
Incompatibility warning with IntelliJ Ultimate or PyCharm 2021.x

### ISSUE THREAD

**Issue by ascheman** [mutl3y/ansibleHelper#18]
When starting current versions of IntelliJ (Ultimate or PyCharm) like 2021.1, I get the following warning:

![image](https://user-images.githubusercontent.com/456000/115248845-54e52800-a128-11eb-8e7d-fe8e58e70b31.png)

The current version claims to have build names/numbers like `PY-211...` or `#IU-211...`, i.e., they have a prefix:

![image](https://user-images.githubusercontent.com/456000/115248989-7c3bf500-a128-11eb-85a0-994ca79a6066.png)

Not sure whether this must be solved by JetBrains?

**Comment by mutl3y** [comment]
thanks for reporting this, I will have a look and see if I can see what's going on

**Comment by mutl3y** [comment]
bumped version numbers new version published on marketplace
